version: "3.8"

services:
  devops-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/integration-nation.dk:/etc/letsencrypt/live/integration-nation.dk
      - /etc/letsencrypt/archive/integration-nation.dk:/etc/letsencrypt/archive/integration-nation.dk
